### ISSUE TITLE
Typescript error on SocketIOCollaborationOptions

### ISSUE THREAD

**Issue by ChrisLincoln** [cudr/slate-collaborative#13]
I think the onDocumentLoad() return type needs to be Promise<Element[]> | Element[]
https://github.com/cudr/slate-collaborative/blob/master/packages/backend/src/SocketIOConnection.ts#L23

**Comment by cudr** [comment]
> I think the onDocumentLoad() return type needs to be Promise<Element[]> | Element[]
> https://github.com/cudr/slate-collaborative/blob/master/packages/backend/src/SocketIOConnection.ts#L23

Sure, but i think 
```ts
Promise<Node[]> | Node[]
``` 
will better?

**Comment by ChrisLincoln** [comment]
Yes, I just checked. That is what I have at the root of my initial document. #14
