### ISSUE TITLE
Ability to get names on backend

### ISSUE THREAD

**Issue by zekenie** [cudr/slate-collaborative#17]
Hi there!

I'm really enjoying playing around with this project. I think it'd be great if there were a way to resolve the cursor name on the backend instead of the frontend. In my case, I want to send a jwt to the backend over a websocket and then use that to resolve a name, instead of trusting the client.

**Comment by cudr** [comment]
Hi @zekenie!

This is the interesting point! I think we need modify onAuthRequest function to return an object with user data for that.

**Comment by zekenie** [comment]
I was actually able to solve this in a hacky way by throwing if data didn't match in the `onAuthRequest`
