### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by zhangjq12** [cudr/slate-collaborative#47]
**Device (please complete the following information):**
 - OS: MacOS
 - Browser: chrome 87.0.4280.88
 - Version of slate 0.59.0
 - Version of slate-collaborative 0.7.0

**Describe the bug**
When I import the slate-collaborative in my project, it's caught an error when running: ReferenceError: regeneratorRuntime is not defined. This error occurs at automerge-editor.ts and I can't solve this even I add transform-runtime at babel configuration.

**Comment by MaltesBytes** [comment]
I'm having this issue as well. What was the solution?
