### ISSUE TITLE
QUESTION: Real Time Database as backend

### ISSUE THREAD

**Issue by cngeru** [cudr/slate-collaborative#52]
Is it possible to use the firebase realtime database as the backend ?

**Comment by cudr** [comment]
Yes, sure. You need NodeJS firebase rest client, and connect [slate-collaborative/backend](https://github.com/cudr/slate-collaborative#backend) methods onDocumentLoad and onDocumentSave with your firebase entities query.

**Comment by cngeru** [comment]
I can't find the rest client.. Or is it just the regular firebase package ?
Is there an example code snippet with this  and will the data be streamed to the other clients ?
Can once sync with the db after an event (onClick) or intervals to reduce the number of calls?

**Comment by cngeru** [comment]
Is there an example using JS ?

**Comment by cudr** [comment]
@cngeru I mean firebase-admin nodejs sdk. You could read more [here](https://firebase.google.com/docs/admin/setup)

**Comment by cngeru** [comment]
@cudr can I use the real time database `Read data once` capability to read the initial data then `listen for updates `on the documents.
Is this possible and where would I connect the function ?
Instead of having real time updates how do I implement the sync with a click of a button ?
