### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by jcleyba** [cudr/slate-collaborative#7]
Hi! Love this plugin!! I cannot make it work with latest Slate API and the plugins example in the docs:
https://docs.slatejs.org/concepts/07-plugins

Will this plugin work with the latest Slate API? Can the plugin documentation be updated?

Thanks

**Comment by cudr** [comment]
@jcleyba, Thank you! Yes, now this plugin doesn't works with latest Slate version.

Hope to find time soon and update it

**Comment by dedan** [comment]
That plugin would also be immensely useful for my current work. Any updates on making it work with the latest Slate version? @cudr 

Thanks a lot for the great work!

**Comment by cudr** [comment]
@dedan @jcleyba already updated for latest slate version.
