### ISSUE TITLE
Port to Slate 0.5x

### ISSUE THREAD

**Issue by dselman** [cudr/slate-collaborative#9]
Are there any plans to port this to Slate 0.5x?

**Comment by cudr** [comment]
> Are there any plans to port this to Slate 0.5x?

@dselman, sure. I have plan to upgrade it

**Comment by cudr** [comment]
I thinking

> what is your plan @cudr? can we help?
> 
> this might be something I would need to use soon on my app, I'm happy to help if you need some

I plan to refactor it. I don’t really like the tough bunch of APIs (socketIO) and the core logic in the current implementation. I want to separate this logic and rewrite everything using hooks. I think I can do this soon, wait a bit

**Comment by dselman** [comment]
Awesome. Happy to help with testing.

**Comment by horacioh** [comment]
@cudr perfect!
any help please reach out to me!

**Comment by cudr** [comment]
@dselman @horacioh already updated for latest slate version.

**Comment by horacioh** [comment]
thanks!! will check this out!
